// import type { Metadata } from "next";
// import { Noto_Serif_Bengali } from "next/font/google";
// import "./globals.css";
// import { ToastContainer } from "react-toastify";
// import Navbar from "@/components/header/Navbar";
// import HeaderBottom from "@/components/header/HeaderBottom";

// const notoSerifBengali = Noto_Serif_Bengali({
//   subsets: ["latin", 'bengali'],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }: LayoutProps<"/">) {
//   return (
//     <html
//       lang="en"
//       data-theme="light"
//       className={`${notoSerifBengali.className} h-full antialiased bg-(--bg-blue-200)`}
//     >
//       <body className="min-h-full flex flex-col">
//         <Navbar />
//         <HeaderBottom />

//         <main>
//           {children}
//         </main>

//         <ToastContainer />
//       </body>
//     </html>
//   );
// }







// import type { Metadata } from "next";
// import { Noto_Serif_Bengali } from "next/font/google";
// import "./globals.css";
// import { ToastContainer } from "react-toastify";
// import Navbar from "@/components/header/Navbar";
// import HeaderBottom from "@/components/header/HeaderBottom";

// const notoSerifBengali = Noto_Serif_Bengali({
//   subsets: ["latin", "bengali"],
// });

// export const metadata: Metadata = {
//   title: "বাজার দর",
//   description: "বাংলাদেশের নিত্যপ্রয়োজনীয় পণ্যের বাজার দর",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{ children: React.ReactNode }>) {
//   return (
//     <html
//       lang="bn"
//       data-theme="light"
//       className={`${notoSerifBengali.className} h-full antialiased bg-(--bg-blue-200)`}
//     >
//       <body className="min-h-full flex flex-col">
//         <Navbar />
//         <HeaderBottom />

//         <main>{children}</main>

//         <ToastContainer />
//       </body>
//     </html>
//   );
// }







import type { Metadata } from "next";
import { Suspense } from "react";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import Navbar from "@/components/header/Navbar";
import HeaderBottom from "@/components/header/HeaderBottom";

const notoSerifBengali = Noto_Serif_Bengali({
  subsets: ["latin", "bengali"],
});

export const metadata: Metadata = {
  title: "বাজার দর",
  description: "বাংলাদেশের নিত্যপ্রয়োজনীয় পণ্যের বাজার দর",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="bn"
      data-theme="light"
      className={`${notoSerifBengali.className} h-full antialiased bg-(--bg-blue-200)`}
    >
      <body className="min-h-full flex flex-col">
        <Suspense fallback={<div className="min-h-20" />}>
          <Navbar />
        </Suspense>

        <Suspense fallback={<div className="min-h-10" />}>
          <HeaderBottom />
        </Suspense>

        <main>{children}</main>

        <ToastContainer />
      </body>
    </html>
  );
}